apiVersion: v1
kind: Secret
metadata:
  name: ms1-mariadb
  namespace: jdemo
  labels:
    app: ms1-mariadb
type: Opaque
data:
  mariadb-root-password: YzlhZDdhNWZhMTQxMDY0NGEwMDYzNjQxYWFhYmQ5YjY5Mzg0YjY5ZTU4MDBiZmIxNDljMDQ0NjQwYWRhMTFiMjFiYzhkNjdmNmVkYWJlM2M5YjVkMDI4MDc1MDIzZWNkMWY1MmIxZGI0ZWU4MTU4YzMwN2JmOWNjOTMyYTUzZTc2ZjI4YzM0NDYzOTRiNzg2N2RlNGYxMjQxMTQ1OThjNzExODVhNjA5OTU5Y2M2MjA0ZWIwNzQ5YTY5ZTBhZWQwNWVmMWUwMGQyNDJlOTI5YjBlNWFjNmQ3YjYzYWY1ZDllNzFlN2Q1MjJkOTE1MzlkMTcwMGE0YzRmNzMyMjM1Yg==
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms1-mariadb
  namespace: jdemo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms1-mariadb
  template:
    metadata:
      labels:
        app: ms1-mariadb
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: mariadb
          image: mariadb:10.4.7
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms1-mariadb
                  key: mariadb-root-password
            - name: MYSQL_DATABASE
              value: ms1
          #        command:
          #        - mysqld
          #        - --lower_case_table_names=1
          #        - --skip-ssl
          #        - --character_set_server=utf8mb4
          #        - --explicit_defaults_for_timestamp
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: data
              mountPath: /var/lib/mysql/
---
apiVersion: v1
kind: Service
metadata:
  name: ms1-mariadb
  namespace: jdemo
spec:
  selector:
    app: ms1-mariadb
  ports:
    - port: 3306
